services:
  ms-reservas:
    container_name: ms-reservas
    image: alexissuarez27/ms-reservas:latest

    restart: always
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
    volumes:
      - ./logs:/app/reservas/src/utils/general/LOGS
    networks:
      - reservas-network

networks:
  reservas-network:
    driver: bridge