
services:
  ms-administracion:
    container_name: ms-administracion
    image: engineermerchan/ms-administracion:latest
    restart: always
    ports:
      - '10103:10103'
    volumes:

      - ./logs-admin:/app/MS-Administracion/src/utils/general/LOGS
    networks:
      - proyecto-network

networks:
  proyecto-network:
    driver: bridge